tools:
  exceptions: "https://sentry.io/organizations/dcsil/projects/konsensus-frontend/?project=6253111"
  logging: ""
  ci: ""

services:
  production: "https://konsensus-client.herokuapp.com/"

docs:
  frontend: "https://github.com/dcsil/konsensus-app-frontend"
  backend: "https://github.com/dcsil/konsensus-app-backend"

commands:
  bootstrap: "./client/script/bootstrap"
  database: ""
  server: "npm start"
  test: "npm test"

