version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10

general:
  build_dir: konsensus-app-frontend/client

jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: 091a4a1fada85b993a33e76d5656ce94a4ef7bbfac17302cf9be72e4e8a81e02
    docker:
      - image: circleci/node:10.16.3
      - image: trufflesuite/ganache-cli
        command: ganache-cli -i 5777 -p 7545 -e 100000000000 -l 4700038

    working_directory: ~/repo
    steps:
      - checkout
      # install client dependencies
      - run:
          name: Check files
          command: ls
      - run:
          name: Install Client Dependencies
          command: cd client && npm install
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter chmod +x ./cc-test-reporter
      - run:
          name: Run tests and code coverage for client
          command: cd client && npm run test
      - run:
          name: Format Code Coverage
          command: cd client && ../cc-test-reporter format-coverage coverage/lcov.info -t lcov
      - run:
          name: Sum up Code Coverage
          command: |
            ./cc-test-reporter sum-coverage ./client/coverage/codeclimate.json -p 2 -o sum.json
       - run:
          name: Upload Code Coverage
          command: |
            ./cc-test-reporter upload-coverage -i sum.json
      # smart contract commands
      - restore_cache:
          name: Restore npm Package Cache
          working_directory: ./
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Smart Contract Dependencies
          command: npm ci
      - run:
          name: Migrate Contracts
          command: ./node_modules/truffle/build/cli.bundled.js migrate --network development
      - run:
          name: Test Contracts
          command: ./node_modules/truffle/build/cli.bundled.js test --network development
      # - run:
      #     name: Codecheck
      #     command: npx codechecks
      - run:
          name: Code Coverage
          command: npx truffle run coverage
      # - run:
      #     name: Coveralls
      #     command: cat coverage/lcov.info | npx coveralls
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build
          filters:
            branches:
              only: main
