version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10

general:
  build_dir: konsensus-app-frontend/client

jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
      - image: trufflesuite/ganache-cli
        command: ganache-cli -i 5777 -e 100000000000 -l 4700038
    working_directory: ~/repo
    steps:
      - checkout
      # install dependencies
      - run:
          name: Check files
          command: ls
      - run:
          name: Install Dependencies
          command: cd client && npm install
      - run:
          name: Run tests
          command: cd client && npm run test
      - run:
          name: Run smart contract tests
          command: truffle test

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build
          filters:
            branches:
              only: main
