name: Dev deployment from Github to AWS
on:
  push:
    branches:
      - reformat-repo

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: teamkonsensus/konsensus-app-frontend:latest
      
      - name: Get Timestamp
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Generate Deployment Package
        run: zip -r deploy.zip * -x "**node_modules**"

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Konsensus Frontend
          environment_name: Konsensusfrontend-env
          version_label: "docker-app-${{ steps.format-time.outputs.replaced }}"
          region: us-east-1
          deployment_package: deploy.zip
